[default_config]
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86"

[default_config.opts]
compiler = "cc"
compile_flags_txt = []
diagnostics = true
default_diagnostics = false

[[project]]
path = ""
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86"

[project.opts]
compiler = "cc"
compile_flags_txt = []
diagnostics = true
default_diagnostics = false
